require "base-sane"

require "look-colorizer"
require "look-dashboard"
require "look-git"
require "look-statusline"
require "look-statuscolumn"
require "look-todo"
require "look-topline"
require "look-general"

require "ide-ai"
require "ide-completion"
require "ide-dap"
require "ide-lsp"
require "look-lsp"
require "ide-config-schemas"
require "ide-regexplainer"
require "ide-treesitter"
require "ide-formatting"
require "ide-testing"
require "ide-haskell"
require "ide-rust"

require "draw-venn"

require "nav-nvim-tree"
require "nav-project"
require "nav-telescope"
require "nav-which_key"

require "text-surround"
require "text-comment"

require "look-theme"
